version: '3.1'

services:
  mongo:
    container_name: ${MONGO_NAME}
    image: mongo
    restart: unless-stopped
    networks:
      - app-connect
    ports:
      - '${MONGO_PORT}:27017'

networks:
  app-connect:
    driver: bridge
